name: 'Helm Publisher'
description: 'A GitHub Action for publishing Helm charts with Github Pages'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  token:
    description: "GitHub token"
    required: true
  charts_dir:
    description: "The charts directory, defaults to `charts`"
    required: false
  charts_url:
    description: "The GitHub Pages URL, defaults to `https://<OWNER>.github.io/<REPOSITORY>`"
    required: false
  owner:
    description: "The GitHub user or org that owns this repository, defaults to `GITHUB_REPOSITORY`"
    required: false
  repository:
    description: "The GitHub repository name, defaults to `GITHUB_REPOSITORY`"
    required: false
  branch:
    description: "The branch to publish charts, defaults to `gh-pages`"
    required: false
  helm_version:
    description: "The Helm CLI version"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.charts_dir }}
    - ${{ inputs.charts_url }}
    - ${{ inputs.user }}
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.helm_version }}